name: pixiv_shaft
description: Pixiv 桌面客户端，后端为 Rust，界面为 Flutter。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.13.0
  flutter_rust_bridge_hooks: 2.13.0
  file_selector: ^1.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
