name: pixiv_shaft
description: Pixiv 桌面客户端，后端为 Rust，界面为 Flutter。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
