// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/auth.dart';
import 'api/comment.dart';
import 'api/illust.dart';
import 'api/image.dart';
import 'api/novel.dart';
import 'api/store.dart';
import 'api/user.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthSession dco_decode_auth_session(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BrowseRecord dco_decode_browse_record(dynamic raw);

  @protected
  CommentEntry dco_decode_comment_entry(dynamic raw);

  @protected
  CommentPage dco_decode_comment_page(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IllustDetail dco_decode_illust_detail(dynamic raw);

  @protected
  IllustSummary dco_decode_illust_summary(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BrowseRecord> dco_decode_list_browse_record(dynamic raw);

  @protected
  List<CommentEntry> dco_decode_list_comment_entry(dynamic raw);

  @protected
  List<IllustSummary> dco_decode_list_illust_summary(dynamic raw);

  @protected
  List<NovelSummary> dco_decode_list_novel_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SearchRecord> dco_decode_list_search_record(dynamic raw);

  @protected
  List<UserPreview> dco_decode_list_user_preview(dynamic raw);

  @protected
  LoginResult dco_decode_login_result(dynamic raw);

  @protected
  NovelSeries dco_decode_novel_series(dynamic raw);

  @protected
  NovelSummary dco_decode_novel_summary(dynamic raw);

  @protected
  SearchRecord dco_decode_search_record(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserListPage dco_decode_user_list_page(dynamic raw);

  @protected
  UserPreview dco_decode_user_preview(dynamic raw);

  @protected
  UserProfile dco_decode_user_profile(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthSession sse_decode_auth_session(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BrowseRecord sse_decode_browse_record(SseDeserializer deserializer);

  @protected
  CommentEntry sse_decode_comment_entry(SseDeserializer deserializer);

  @protected
  CommentPage sse_decode_comment_page(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IllustDetail sse_decode_illust_detail(SseDeserializer deserializer);

  @protected
  IllustSummary sse_decode_illust_summary(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BrowseRecord> sse_decode_list_browse_record(
    SseDeserializer deserializer,
  );

  @protected
  List<CommentEntry> sse_decode_list_comment_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<IllustSummary> sse_decode_list_illust_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<NovelSummary> sse_decode_list_novel_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SearchRecord> sse_decode_list_search_record(
    SseDeserializer deserializer,
  );

  @protected
  List<UserPreview> sse_decode_list_user_preview(SseDeserializer deserializer);

  @protected
  LoginResult sse_decode_login_result(SseDeserializer deserializer);

  @protected
  NovelSeries sse_decode_novel_series(SseDeserializer deserializer);

  @protected
  NovelSummary sse_decode_novel_summary(SseDeserializer deserializer);

  @protected
  SearchRecord sse_decode_search_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserListPage sse_decode_user_list_page(SseDeserializer deserializer);

  @protected
  UserPreview sse_decode_user_preview(SseDeserializer deserializer);

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_session(AuthSession self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_browse_record(BrowseRecord self, SseSerializer serializer);

  @protected
  void sse_encode_comment_entry(CommentEntry self, SseSerializer serializer);

  @protected
  void sse_encode_comment_page(CommentPage self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_illust_detail(IllustDetail self, SseSerializer serializer);

  @protected
  void sse_encode_illust_summary(IllustSummary self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_browse_record(
    List<BrowseRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comment_entry(
    List<CommentEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_illust_summary(
    List<IllustSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_novel_summary(
    List<NovelSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_search_record(
    List<SearchRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_preview(
    List<UserPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_login_result(LoginResult self, SseSerializer serializer);

  @protected
  void sse_encode_novel_series(NovelSeries self, SseSerializer serializer);

  @protected
  void sse_encode_novel_summary(NovelSummary self, SseSerializer serializer);

  @protected
  void sse_encode_search_record(SearchRecord self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_list_page(UserListPage self, SseSerializer serializer);

  @protected
  void sse_encode_user_preview(UserPreview self, SseSerializer serializer);

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
