// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/auth.dart';
import 'api/comment.dart';
import 'api/illust.dart';
import 'api/image.dart';
import 'api/novel.dart';
import 'api/store.dart';
import 'api/user.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -614604658;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'pixiv_core',
        ioDirectory: 'rust/core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiIllustAddBookmark({
    required PlatformInt64 illustId,
    required String restrict,
  });

  Future<void> crateApiCommentAddIllustComment({
    required PlatformInt64 illustId,
    required String body,
    required PlatformInt64 parentCommentId,
  });

  Future<void> crateApiNovelAddNovelBookmark({
    required PlatformInt64 novelId,
    required String restrict,
  });

  Future<void> crateApiStoreClearBrowse();

  Future<void> crateApiStoreClearSearches();

  Future<LoginResult> crateApiAuthCompleteLogin({
    required String pasted,
    required String codeVerifier,
  });

  Future<void> crateApiStoreDeleteBrowse({
    required String contentType,
    required PlatformInt64 targetId,
  });

  Future<void> crateApiCommentDeleteIllustComment({
    required PlatformInt64 commentId,
  });

  Future<void> crateApiStoreDeleteSearch({required PlatformInt64 id});

  Future<List<IllustSummary>> crateApiIllustFetchBookmarkedIllusts();

  Future<List<NovelSummary>> crateApiNovelFetchBookmarkedNovels();

  Future<UserListPage> crateApiUserFetchFollowerUsers({
    required PlatformInt64 userId,
  });

  Future<UserListPage> crateApiUserFetchFollowingUsers({
    required PlatformInt64 userId,
    required String restrict,
  });

  Future<CommentPage> crateApiCommentFetchIllustComments({
    required PlatformInt64 illustId,
  });

  Future<IllustDetail> crateApiIllustFetchIllustDetail({
    required PlatformInt64 illustId,
  });

  Future<Uint8List> crateApiImageFetchImage({required String url});

  Future<UserListPage> crateApiUserFetchMypixivUsers({
    required PlatformInt64 userId,
  });

  Future<CommentPage> crateApiCommentFetchNextComments({
    required String nextUrl,
  });

  Future<NovelSeries> crateApiNovelFetchNextSeries({required String nextUrl});

  Future<UserListPage> crateApiUserFetchNextUsers({required String nextUrl});

  Future<NovelSummary> crateApiNovelFetchNovelDetail({
    required PlatformInt64 novelId,
  });

  Future<NovelSeries> crateApiNovelFetchNovelSeries({
    required PlatformInt64 seriesId,
  });

  Future<List<IllustSummary>> crateApiIllustFetchRanking({
    required String mode,
  });

  Future<List<IllustSummary>> crateApiIllustFetchRecommendedIllusts();

  Future<List<NovelSummary>> crateApiNovelFetchRecommendedNovels();

  Future<List<IllustSummary>> crateApiIllustFetchRelatedIllusts({
    required PlatformInt64 illustId,
  });

  Future<UserProfile> crateApiUserFetchUserDetail({
    required PlatformInt64 userId,
  });

  Future<List<IllustSummary>> crateApiIllustFetchUserIllusts({
    required PlatformInt64 userId,
    required String illustType,
  });

  Future<void> crateApiUserFollowUser({
    required PlatformInt64 userId,
    required String restrict,
  });

  Future<void> crateApiInitApp();

  Future<bool> crateApiAuthIsLoggedIn();

  Future<List<BrowseRecord>> crateApiStoreListBrowse({
    required String contentType,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<List<SearchRecord>> crateApiStoreListSearches({
    required PlatformInt64 recentLimit,
  });

  Future<void> crateApiAuthLogout();

  Future<void> crateApiStoreRecordBrowse({
    required String contentType,
    required PlatformInt64 targetId,
    required String payloadJson,
  });

  Future<void> crateApiStoreRecordSearch({
    required String keyword,
    required PlatformInt64 searchType,
  });

  Future<void> crateApiIllustRemoveBookmark({required PlatformInt64 illustId});

  Future<void> crateApiNovelRemoveNovelBookmark({
    required PlatformInt64 novelId,
  });

  Future<void> crateApiStoreResetSetting({required String key});

  Future<List<IllustSummary>> crateApiIllustSearchIllusts({
    required String word,
  });

  Future<PlatformInt64> crateApiUserSelfUserId();

  Future<void> crateApiStoreSetSearchPinned({
    required PlatformInt64 id,
    required bool pinned,
  });

  Future<void> crateApiStoreSetSetting({
    required String key,
    required String value,
  });

  Future<String> crateApiStoreSetting({required String key});

  Future<AuthSession> crateApiAuthStartLogin();

  Future<void> crateApiUserUnfollowUser({required PlatformInt64 userId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiIllustAddBookmark({
    required PlatformInt64 illustId,
    required String restrict,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          sse_encode_String(restrict, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustAddBookmarkConstMeta,
        argValues: [illustId, restrict],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustAddBookmarkConstMeta => const TaskConstMeta(
    debugName: "add_bookmark",
    argNames: ["illustId", "restrict"],
  );

  @override
  Future<void> crateApiCommentAddIllustComment({
    required PlatformInt64 illustId,
    required String body,
    required PlatformInt64 parentCommentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          sse_encode_String(body, serializer);
          sse_encode_i_64(parentCommentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCommentAddIllustCommentConstMeta,
        argValues: [illustId, body, parentCommentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentAddIllustCommentConstMeta =>
      const TaskConstMeta(
        debugName: "add_illust_comment",
        argNames: ["illustId", "body", "parentCommentId"],
      );

  @override
  Future<void> crateApiNovelAddNovelBookmark({
    required PlatformInt64 novelId,
    required String restrict,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          sse_encode_String(restrict, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelAddNovelBookmarkConstMeta,
        argValues: [novelId, restrict],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelAddNovelBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "add_novel_bookmark",
        argNames: ["novelId", "restrict"],
      );

  @override
  Future<void> crateApiStoreClearBrowse() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreClearBrowseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreClearBrowseConstMeta =>
      const TaskConstMeta(debugName: "clear_browse", argNames: []);

  @override
  Future<void> crateApiStoreClearSearches() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreClearSearchesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreClearSearchesConstMeta =>
      const TaskConstMeta(debugName: "clear_searches", argNames: []);

  @override
  Future<LoginResult> crateApiAuthCompleteLogin({
    required String pasted,
    required String codeVerifier,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pasted, serializer);
          sse_encode_String(codeVerifier, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_login_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthCompleteLoginConstMeta,
        argValues: [pasted, codeVerifier],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthCompleteLoginConstMeta => const TaskConstMeta(
    debugName: "complete_login",
    argNames: ["pasted", "codeVerifier"],
  );

  @override
  Future<void> crateApiStoreDeleteBrowse({
    required String contentType,
    required PlatformInt64 targetId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentType, serializer);
          sse_encode_i_64(targetId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreDeleteBrowseConstMeta,
        argValues: [contentType, targetId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreDeleteBrowseConstMeta => const TaskConstMeta(
    debugName: "delete_browse",
    argNames: ["contentType", "targetId"],
  );

  @override
  Future<void> crateApiCommentDeleteIllustComment({
    required PlatformInt64 commentId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(commentId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCommentDeleteIllustCommentConstMeta,
        argValues: [commentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentDeleteIllustCommentConstMeta =>
      const TaskConstMeta(
        debugName: "delete_illust_comment",
        argNames: ["commentId"],
      );

  @override
  Future<void> crateApiStoreDeleteSearch({required PlatformInt64 id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreDeleteSearchConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreDeleteSearchConstMeta =>
      const TaskConstMeta(debugName: "delete_search", argNames: ["id"]);

  @override
  Future<List<IllustSummary>> crateApiIllustFetchBookmarkedIllusts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchBookmarkedIllustsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchBookmarkedIllustsConstMeta =>
      const TaskConstMeta(debugName: "fetch_bookmarked_illusts", argNames: []);

  @override
  Future<List<NovelSummary>> crateApiNovelFetchBookmarkedNovels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_novel_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelFetchBookmarkedNovelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelFetchBookmarkedNovelsConstMeta =>
      const TaskConstMeta(debugName: "fetch_bookmarked_novels", argNames: []);

  @override
  Future<UserListPage> crateApiUserFetchFollowerUsers({
    required PlatformInt64 userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_list_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFetchFollowerUsersConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFetchFollowerUsersConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_follower_users",
        argNames: ["userId"],
      );

  @override
  Future<UserListPage> crateApiUserFetchFollowingUsers({
    required PlatformInt64 userId,
    required String restrict,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          sse_encode_String(restrict, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_list_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFetchFollowingUsersConstMeta,
        argValues: [userId, restrict],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFetchFollowingUsersConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_following_users",
        argNames: ["userId", "restrict"],
      );

  @override
  Future<CommentPage> crateApiCommentFetchIllustComments({
    required PlatformInt64 illustId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comment_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCommentFetchIllustCommentsConstMeta,
        argValues: [illustId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentFetchIllustCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_illust_comments",
        argNames: ["illustId"],
      );

  @override
  Future<IllustDetail> crateApiIllustFetchIllustDetail({
    required PlatformInt64 illustId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_illust_detail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchIllustDetailConstMeta,
        argValues: [illustId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchIllustDetailConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_illust_detail",
        argNames: ["illustId"],
      );

  @override
  Future<Uint8List> crateApiImageFetchImage({required String url}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageFetchImageConstMeta,
        argValues: [url],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageFetchImageConstMeta =>
      const TaskConstMeta(debugName: "fetch_image", argNames: ["url"]);

  @override
  Future<UserListPage> crateApiUserFetchMypixivUsers({
    required PlatformInt64 userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_list_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFetchMypixivUsersConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFetchMypixivUsersConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_mypixiv_users",
        argNames: ["userId"],
      );

  @override
  Future<CommentPage> crateApiCommentFetchNextComments({
    required String nextUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nextUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_comment_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCommentFetchNextCommentsConstMeta,
        argValues: [nextUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCommentFetchNextCommentsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_next_comments",
        argNames: ["nextUrl"],
      );

  @override
  Future<NovelSeries> crateApiNovelFetchNextSeries({required String nextUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nextUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_novel_series,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelFetchNextSeriesConstMeta,
        argValues: [nextUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelFetchNextSeriesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_next_series",
        argNames: ["nextUrl"],
      );

  @override
  Future<UserListPage> crateApiUserFetchNextUsers({required String nextUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nextUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_list_page,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFetchNextUsersConstMeta,
        argValues: [nextUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFetchNextUsersConstMeta =>
      const TaskConstMeta(debugName: "fetch_next_users", argNames: ["nextUrl"]);

  @override
  Future<NovelSummary> crateApiNovelFetchNovelDetail({
    required PlatformInt64 novelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_novel_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelFetchNovelDetailConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelFetchNovelDetailConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_novel_detail",
        argNames: ["novelId"],
      );

  @override
  Future<NovelSeries> crateApiNovelFetchNovelSeries({
    required PlatformInt64 seriesId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(seriesId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_novel_series,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelFetchNovelSeriesConstMeta,
        argValues: [seriesId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelFetchNovelSeriesConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_novel_series",
        argNames: ["seriesId"],
      );

  @override
  Future<List<IllustSummary>> crateApiIllustFetchRanking({
    required String mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchRankingConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchRankingConstMeta =>
      const TaskConstMeta(debugName: "fetch_ranking", argNames: ["mode"]);

  @override
  Future<List<IllustSummary>> crateApiIllustFetchRecommendedIllusts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchRecommendedIllustsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchRecommendedIllustsConstMeta =>
      const TaskConstMeta(debugName: "fetch_recommended_illusts", argNames: []);

  @override
  Future<List<NovelSummary>> crateApiNovelFetchRecommendedNovels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_novel_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelFetchRecommendedNovelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelFetchRecommendedNovelsConstMeta =>
      const TaskConstMeta(debugName: "fetch_recommended_novels", argNames: []);

  @override
  Future<List<IllustSummary>> crateApiIllustFetchRelatedIllusts({
    required PlatformInt64 illustId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchRelatedIllustsConstMeta,
        argValues: [illustId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchRelatedIllustsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_related_illusts",
        argNames: ["illustId"],
      );

  @override
  Future<UserProfile> crateApiUserFetchUserDetail({
    required PlatformInt64 userId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_user_profile,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFetchUserDetailConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFetchUserDetailConstMeta =>
      const TaskConstMeta(debugName: "fetch_user_detail", argNames: ["userId"]);

  @override
  Future<List<IllustSummary>> crateApiIllustFetchUserIllusts({
    required PlatformInt64 userId,
    required String illustType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          sse_encode_String(illustType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustFetchUserIllustsConstMeta,
        argValues: [userId, illustType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustFetchUserIllustsConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_user_illusts",
        argNames: ["userId", "illustType"],
      );

  @override
  Future<void> crateApiUserFollowUser({
    required PlatformInt64 userId,
    required String restrict,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          sse_encode_String(restrict, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserFollowUserConstMeta,
        argValues: [userId, restrict],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserFollowUserConstMeta => const TaskConstMeta(
    debugName: "follow_user",
    argNames: ["userId", "restrict"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiAuthIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "is_logged_in", argNames: []);

  @override
  Future<List<BrowseRecord>> crateApiStoreListBrowse({
    required String contentType,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentType, serializer);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_browse_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreListBrowseConstMeta,
        argValues: [contentType, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreListBrowseConstMeta => const TaskConstMeta(
    debugName: "list_browse",
    argNames: ["contentType", "limit", "offset"],
  );

  @override
  Future<List<SearchRecord>> crateApiStoreListSearches({
    required PlatformInt64 recentLimit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(recentLimit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_search_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreListSearchesConstMeta,
        argValues: [recentLimit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreListSearchesConstMeta => const TaskConstMeta(
    debugName: "list_searches",
    argNames: ["recentLimit"],
  );

  @override
  Future<void> crateApiAuthLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAuthLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<void> crateApiStoreRecordBrowse({
    required String contentType,
    required PlatformInt64 targetId,
    required String payloadJson,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(contentType, serializer);
          sse_encode_i_64(targetId, serializer);
          sse_encode_String(payloadJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreRecordBrowseConstMeta,
        argValues: [contentType, targetId, payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreRecordBrowseConstMeta => const TaskConstMeta(
    debugName: "record_browse",
    argNames: ["contentType", "targetId", "payloadJson"],
  );

  @override
  Future<void> crateApiStoreRecordSearch({
    required String keyword,
    required PlatformInt64 searchType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(keyword, serializer);
          sse_encode_i_64(searchType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreRecordSearchConstMeta,
        argValues: [keyword, searchType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreRecordSearchConstMeta => const TaskConstMeta(
    debugName: "record_search",
    argNames: ["keyword", "searchType"],
  );

  @override
  Future<void> crateApiIllustRemoveBookmark({required PlatformInt64 illustId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(illustId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustRemoveBookmarkConstMeta,
        argValues: [illustId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustRemoveBookmarkConstMeta =>
      const TaskConstMeta(debugName: "remove_bookmark", argNames: ["illustId"]);

  @override
  Future<void> crateApiNovelRemoveNovelBookmark({
    required PlatformInt64 novelId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(novelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiNovelRemoveNovelBookmarkConstMeta,
        argValues: [novelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNovelRemoveNovelBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "remove_novel_bookmark",
        argNames: ["novelId"],
      );

  @override
  Future<void> crateApiStoreResetSetting({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreResetSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreResetSettingConstMeta =>
      const TaskConstMeta(debugName: "reset_setting", argNames: ["key"]);

  @override
  Future<List<IllustSummary>> crateApiIllustSearchIllusts({
    required String word,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(word, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_illust_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIllustSearchIllustsConstMeta,
        argValues: [word],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIllustSearchIllustsConstMeta =>
      const TaskConstMeta(debugName: "search_illusts", argNames: ["word"]);

  @override
  Future<PlatformInt64> crateApiUserSelfUserId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserSelfUserIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserSelfUserIdConstMeta =>
      const TaskConstMeta(debugName: "self_user_id", argNames: []);

  @override
  Future<void> crateApiStoreSetSearchPinned({
    required PlatformInt64 id,
    required bool pinned,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(id, serializer);
          sse_encode_bool(pinned, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreSetSearchPinnedConstMeta,
        argValues: [id, pinned],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreSetSearchPinnedConstMeta =>
      const TaskConstMeta(
        debugName: "set_search_pinned",
        argNames: ["id", "pinned"],
      );

  @override
  Future<void> crateApiStoreSetSetting({
    required String key,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreSetSettingConstMeta,
        argValues: [key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreSetSettingConstMeta =>
      const TaskConstMeta(debugName: "set_setting", argNames: ["key", "value"]);

  @override
  Future<String> crateApiStoreSetting({required String key}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStoreSettingConstMeta,
        argValues: [key],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStoreSettingConstMeta =>
      const TaskConstMeta(debugName: "setting", argNames: ["key"]);

  @override
  Future<AuthSession> crateApiAuthStartLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_auth_session,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAuthStartLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAuthStartLoginConstMeta =>
      const TaskConstMeta(debugName: "start_login", argNames: []);

  @override
  Future<void> crateApiUserUnfollowUser({required PlatformInt64 userId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(userId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUserUnfollowUserConstMeta,
        argValues: [userId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUserUnfollowUserConstMeta =>
      const TaskConstMeta(debugName: "unfollow_user", argNames: ["userId"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthSession dco_decode_auth_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AuthSession(
      authUrl: dco_decode_String(arr[0]),
      codeVerifier: dco_decode_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BrowseRecord dco_decode_browse_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BrowseRecord(
      contentType: dco_decode_String(arr[0]),
      targetId: dco_decode_i_64(arr[1]),
      payloadJson: dco_decode_String(arr[2]),
      viewedAt: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  CommentEntry dco_decode_comment_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CommentEntry(
      id: dco_decode_i_64(arr[0]),
      body: dco_decode_String(arr[1]),
      date: dco_decode_String(arr[2]),
      authorId: dco_decode_i_64(arr[3]),
      authorName: dco_decode_String(arr[4]),
      avatarUrl: dco_decode_String(arr[5]),
      hasReplies: dco_decode_bool(arr[6]),
    );
  }

  @protected
  CommentPage dco_decode_comment_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CommentPage(
      comments: dco_decode_list_comment_entry(arr[0]),
      nextUrl: dco_decode_String(arr[1]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  IllustDetail dco_decode_illust_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return IllustDetail(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      authorId: dco_decode_i_64(arr[2]),
      authorName: dco_decode_String(arr[3]),
      caption: dco_decode_String(arr[4]),
      pageCount: dco_decode_i_64(arr[5]),
      width: dco_decode_i_64(arr[6]),
      height: dco_decode_i_64(arr[7]),
      totalBookmarks: dco_decode_i_64(arr[8]),
      totalView: dco_decode_i_64(arr[9]),
      isBookmarked: dco_decode_bool(arr[10]),
      tags: dco_decode_list_String(arr[11]),
      imageUrls: dco_decode_list_String(arr[12]),
    );
  }

  @protected
  IllustSummary dco_decode_illust_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return IllustSummary(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      authorId: dco_decode_i_64(arr[2]),
      authorName: dco_decode_String(arr[3]),
      pageCount: dco_decode_i_64(arr[4]),
      imageUrl: dco_decode_String(arr[5]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BrowseRecord> dco_decode_list_browse_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_browse_record).toList();
  }

  @protected
  List<CommentEntry> dco_decode_list_comment_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_comment_entry).toList();
  }

  @protected
  List<IllustSummary> dco_decode_list_illust_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_illust_summary).toList();
  }

  @protected
  List<NovelSummary> dco_decode_list_novel_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_novel_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SearchRecord> dco_decode_list_search_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_search_record).toList();
  }

  @protected
  List<UserPreview> dco_decode_list_user_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user_preview).toList();
  }

  @protected
  LoginResult dco_decode_login_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LoginResult(
      userId: dco_decode_i_64(arr[0]),
      userName: dco_decode_String(arr[1]),
    );
  }

  @protected
  NovelSeries dco_decode_novel_series(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return NovelSeries(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      caption: dco_decode_String(arr[2]),
      isConcluded: dco_decode_bool(arr[3]),
      isWatched: dco_decode_bool(arr[4]),
      chapters: dco_decode_list_novel_summary(arr[5]),
      nextUrl: dco_decode_String(arr[6]),
    );
  }

  @protected
  NovelSummary dco_decode_novel_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return NovelSummary(
      id: dco_decode_i_64(arr[0]),
      title: dco_decode_String(arr[1]),
      caption: dco_decode_String(arr[2]),
      createDate: dco_decode_String(arr[3]),
      textLength: dco_decode_i_64(arr[4]),
      totalBookmarks: dco_decode_i_64(arr[5]),
      totalView: dco_decode_i_64(arr[6]),
      isBookmarked: dco_decode_bool(arr[7]),
      coverUrl: dco_decode_String(arr[8]),
      authorId: dco_decode_i_64(arr[9]),
      authorName: dco_decode_String(arr[10]),
      seriesId: dco_decode_i_64(arr[11]),
      seriesTitle: dco_decode_String(arr[12]),
      tags: dco_decode_list_String(arr[13]),
    );
  }

  @protected
  SearchRecord dco_decode_search_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchRecord(
      id: dco_decode_i_64(arr[0]),
      keyword: dco_decode_String(arr[1]),
      searchTime: dco_decode_i_64(arr[2]),
      searchType: dco_decode_i_64(arr[3]),
      pinned: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserListPage dco_decode_user_list_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return UserListPage(
      users: dco_decode_list_user_preview(arr[0]),
      nextUrl: dco_decode_String(arr[1]),
    );
  }

  @protected
  UserPreview dco_decode_user_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return UserPreview(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      account: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_String(arr[3]),
      isFollowed: dco_decode_bool(arr[4]),
      latestIllustUrl: dco_decode_String(arr[5]),
    );
  }

  @protected
  UserProfile dco_decode_user_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return UserProfile(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      account: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_String(arr[3]),
      webpage: dco_decode_String(arr[4]),
      totalIllusts: dco_decode_i_64(arr[5]),
      totalManga: dco_decode_i_64(arr[6]),
      totalNovels: dco_decode_i_64(arr[7]),
      isFollowed: dco_decode_bool(arr[8]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthSession sse_decode_auth_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_authUrl = sse_decode_String(deserializer);
    var var_codeVerifier = sse_decode_String(deserializer);
    return AuthSession(authUrl: var_authUrl, codeVerifier: var_codeVerifier);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BrowseRecord sse_decode_browse_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_contentType = sse_decode_String(deserializer);
    var var_targetId = sse_decode_i_64(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    var var_viewedAt = sse_decode_i_64(deserializer);
    return BrowseRecord(
      contentType: var_contentType,
      targetId: var_targetId,
      payloadJson: var_payloadJson,
      viewedAt: var_viewedAt,
    );
  }

  @protected
  CommentEntry sse_decode_comment_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_body = sse_decode_String(deserializer);
    var var_date = sse_decode_String(deserializer);
    var var_authorId = sse_decode_i_64(deserializer);
    var var_authorName = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_hasReplies = sse_decode_bool(deserializer);
    return CommentEntry(
      id: var_id,
      body: var_body,
      date: var_date,
      authorId: var_authorId,
      authorName: var_authorName,
      avatarUrl: var_avatarUrl,
      hasReplies: var_hasReplies,
    );
  }

  @protected
  CommentPage sse_decode_comment_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_comments = sse_decode_list_comment_entry(deserializer);
    var var_nextUrl = sse_decode_String(deserializer);
    return CommentPage(comments: var_comments, nextUrl: var_nextUrl);
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  IllustDetail sse_decode_illust_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_authorId = sse_decode_i_64(deserializer);
    var var_authorName = sse_decode_String(deserializer);
    var var_caption = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_64(deserializer);
    var var_width = sse_decode_i_64(deserializer);
    var var_height = sse_decode_i_64(deserializer);
    var var_totalBookmarks = sse_decode_i_64(deserializer);
    var var_totalView = sse_decode_i_64(deserializer);
    var var_isBookmarked = sse_decode_bool(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_imageUrls = sse_decode_list_String(deserializer);
    return IllustDetail(
      id: var_id,
      title: var_title,
      authorId: var_authorId,
      authorName: var_authorName,
      caption: var_caption,
      pageCount: var_pageCount,
      width: var_width,
      height: var_height,
      totalBookmarks: var_totalBookmarks,
      totalView: var_totalView,
      isBookmarked: var_isBookmarked,
      tags: var_tags,
      imageUrls: var_imageUrls,
    );
  }

  @protected
  IllustSummary sse_decode_illust_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_authorId = sse_decode_i_64(deserializer);
    var var_authorName = sse_decode_String(deserializer);
    var var_pageCount = sse_decode_i_64(deserializer);
    var var_imageUrl = sse_decode_String(deserializer);
    return IllustSummary(
      id: var_id,
      title: var_title,
      authorId: var_authorId,
      authorName: var_authorName,
      pageCount: var_pageCount,
      imageUrl: var_imageUrl,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BrowseRecord> sse_decode_list_browse_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BrowseRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_browse_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<CommentEntry> sse_decode_list_comment_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CommentEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_comment_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<IllustSummary> sse_decode_list_illust_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IllustSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_illust_summary(deserializer));
    }
    return ans_;
  }

  @protected
  List<NovelSummary> sse_decode_list_novel_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NovelSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_novel_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SearchRecord> sse_decode_list_search_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SearchRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_search_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<UserPreview> sse_decode_list_user_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UserPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user_preview(deserializer));
    }
    return ans_;
  }

  @protected
  LoginResult sse_decode_login_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userId = sse_decode_i_64(deserializer);
    var var_userName = sse_decode_String(deserializer);
    return LoginResult(userId: var_userId, userName: var_userName);
  }

  @protected
  NovelSeries sse_decode_novel_series(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_caption = sse_decode_String(deserializer);
    var var_isConcluded = sse_decode_bool(deserializer);
    var var_isWatched = sse_decode_bool(deserializer);
    var var_chapters = sse_decode_list_novel_summary(deserializer);
    var var_nextUrl = sse_decode_String(deserializer);
    return NovelSeries(
      id: var_id,
      title: var_title,
      caption: var_caption,
      isConcluded: var_isConcluded,
      isWatched: var_isWatched,
      chapters: var_chapters,
      nextUrl: var_nextUrl,
    );
  }

  @protected
  NovelSummary sse_decode_novel_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_caption = sse_decode_String(deserializer);
    var var_createDate = sse_decode_String(deserializer);
    var var_textLength = sse_decode_i_64(deserializer);
    var var_totalBookmarks = sse_decode_i_64(deserializer);
    var var_totalView = sse_decode_i_64(deserializer);
    var var_isBookmarked = sse_decode_bool(deserializer);
    var var_coverUrl = sse_decode_String(deserializer);
    var var_authorId = sse_decode_i_64(deserializer);
    var var_authorName = sse_decode_String(deserializer);
    var var_seriesId = sse_decode_i_64(deserializer);
    var var_seriesTitle = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return NovelSummary(
      id: var_id,
      title: var_title,
      caption: var_caption,
      createDate: var_createDate,
      textLength: var_textLength,
      totalBookmarks: var_totalBookmarks,
      totalView: var_totalView,
      isBookmarked: var_isBookmarked,
      coverUrl: var_coverUrl,
      authorId: var_authorId,
      authorName: var_authorName,
      seriesId: var_seriesId,
      seriesTitle: var_seriesTitle,
      tags: var_tags,
    );
  }

  @protected
  SearchRecord sse_decode_search_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_keyword = sse_decode_String(deserializer);
    var var_searchTime = sse_decode_i_64(deserializer);
    var var_searchType = sse_decode_i_64(deserializer);
    var var_pinned = sse_decode_bool(deserializer);
    return SearchRecord(
      id: var_id,
      keyword: var_keyword,
      searchTime: var_searchTime,
      searchType: var_searchType,
      pinned: var_pinned,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserListPage sse_decode_user_list_page(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_users = sse_decode_list_user_preview(deserializer);
    var var_nextUrl = sse_decode_String(deserializer);
    return UserListPage(users: var_users, nextUrl: var_nextUrl);
  }

  @protected
  UserPreview sse_decode_user_preview(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_account = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_isFollowed = sse_decode_bool(deserializer);
    var var_latestIllustUrl = sse_decode_String(deserializer);
    return UserPreview(
      id: var_id,
      name: var_name,
      account: var_account,
      avatarUrl: var_avatarUrl,
      isFollowed: var_isFollowed,
      latestIllustUrl: var_latestIllustUrl,
    );
  }

  @protected
  UserProfile sse_decode_user_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_account = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_String(deserializer);
    var var_webpage = sse_decode_String(deserializer);
    var var_totalIllusts = sse_decode_i_64(deserializer);
    var var_totalManga = sse_decode_i_64(deserializer);
    var var_totalNovels = sse_decode_i_64(deserializer);
    var var_isFollowed = sse_decode_bool(deserializer);
    return UserProfile(
      id: var_id,
      name: var_name,
      account: var_account,
      avatarUrl: var_avatarUrl,
      webpage: var_webpage,
      totalIllusts: var_totalIllusts,
      totalManga: var_totalManga,
      totalNovels: var_totalNovels,
      isFollowed: var_isFollowed,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_session(AuthSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.authUrl, serializer);
    sse_encode_String(self.codeVerifier, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_browse_record(BrowseRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.contentType, serializer);
    sse_encode_i_64(self.targetId, serializer);
    sse_encode_String(self.payloadJson, serializer);
    sse_encode_i_64(self.viewedAt, serializer);
  }

  @protected
  void sse_encode_comment_entry(CommentEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.body, serializer);
    sse_encode_String(self.date, serializer);
    sse_encode_i_64(self.authorId, serializer);
    sse_encode_String(self.authorName, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_bool(self.hasReplies, serializer);
  }

  @protected
  void sse_encode_comment_page(CommentPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_comment_entry(self.comments, serializer);
    sse_encode_String(self.nextUrl, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_illust_detail(IllustDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.authorId, serializer);
    sse_encode_String(self.authorName, serializer);
    sse_encode_String(self.caption, serializer);
    sse_encode_i_64(self.pageCount, serializer);
    sse_encode_i_64(self.width, serializer);
    sse_encode_i_64(self.height, serializer);
    sse_encode_i_64(self.totalBookmarks, serializer);
    sse_encode_i_64(self.totalView, serializer);
    sse_encode_bool(self.isBookmarked, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_list_String(self.imageUrls, serializer);
  }

  @protected
  void sse_encode_illust_summary(IllustSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_i_64(self.authorId, serializer);
    sse_encode_String(self.authorName, serializer);
    sse_encode_i_64(self.pageCount, serializer);
    sse_encode_String(self.imageUrl, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_browse_record(
    List<BrowseRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_browse_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_comment_entry(
    List<CommentEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_comment_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_illust_summary(
    List<IllustSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_illust_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_novel_summary(
    List<NovelSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_novel_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_search_record(
    List<SearchRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_search_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_user_preview(
    List<UserPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_login_result(LoginResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.userId, serializer);
    sse_encode_String(self.userName, serializer);
  }

  @protected
  void sse_encode_novel_series(NovelSeries self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.caption, serializer);
    sse_encode_bool(self.isConcluded, serializer);
    sse_encode_bool(self.isWatched, serializer);
    sse_encode_list_novel_summary(self.chapters, serializer);
    sse_encode_String(self.nextUrl, serializer);
  }

  @protected
  void sse_encode_novel_summary(NovelSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.caption, serializer);
    sse_encode_String(self.createDate, serializer);
    sse_encode_i_64(self.textLength, serializer);
    sse_encode_i_64(self.totalBookmarks, serializer);
    sse_encode_i_64(self.totalView, serializer);
    sse_encode_bool(self.isBookmarked, serializer);
    sse_encode_String(self.coverUrl, serializer);
    sse_encode_i_64(self.authorId, serializer);
    sse_encode_String(self.authorName, serializer);
    sse_encode_i_64(self.seriesId, serializer);
    sse_encode_String(self.seriesTitle, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_search_record(SearchRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.keyword, serializer);
    sse_encode_i_64(self.searchTime, serializer);
    sse_encode_i_64(self.searchType, serializer);
    sse_encode_bool(self.pinned, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_list_page(UserListPage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_user_preview(self.users, serializer);
    sse_encode_String(self.nextUrl, serializer);
  }

  @protected
  void sse_encode_user_preview(UserPreview self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_bool(self.isFollowed, serializer);
    sse_encode_String(self.latestIllustUrl, serializer);
  }

  @protected
  void sse_encode_user_profile(UserProfile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.account, serializer);
    sse_encode_String(self.avatarUrl, serializer);
    sse_encode_String(self.webpage, serializer);
    sse_encode_i_64(self.totalIllusts, serializer);
    sse_encode_i_64(self.totalManga, serializer);
    sse_encode_i_64(self.totalNovels, serializer);
    sse_encode_bool(self.isFollowed, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
