[package]
name = "ech-inline"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.23"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
webpki-root-certs = "1.0"
base64 = "0.22"

[dependencies.reqwest]
version = "0.13.4"
default-features = false
features = ["rustls", "http2", "query", "charset", "gzip", "json"]

[profile.release]
debug = true
