// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 生成授权地址。界面层负责用系统浏览器打开它。
Future<AuthSession> startLogin() =>
    RustLib.instance.api.crateApiAuthStartLogin();

/// 用用户粘贴的回调地址（或裸授权码）换取 token 并建立会话。
Future<LoginResult> completeLogin({
  required String pasted,
  required String codeVerifier,
}) => RustLib.instance.api.crateApiAuthCompleteLogin(
  pasted: pasted,
  codeVerifier: codeVerifier,
);

/// 当前是否已登录。首次调用时会尝试从钥匙串恢复上次的登录态。
Future<bool> isLoggedIn() => RustLib.instance.api.crateApiAuthIsLoggedIn();

/// 退出登录，同时清掉钥匙串里的凭据。
Future<void> logout() => RustLib.instance.api.crateApiAuthLogout();

/// 一次授权会话：浏览器要打开的授权地址，以及换取 token 时要用到的 verifier。
class AuthSession {
  final String authUrl;
  final String codeVerifier;

  const AuthSession({required this.authUrl, required this.codeVerifier});

  @override
  int get hashCode => authUrl.hashCode ^ codeVerifier.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthSession &&
          runtimeType == other.runtimeType &&
          authUrl == other.authUrl &&
          codeVerifier == other.codeVerifier;
}

class LoginResult {
  final PlatformInt64 userId;
  final String userName;

  const LoginResult({required this.userId, required this.userName});

  @override
  int get hashCode => userId.hashCode ^ userName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoginResult &&
          runtimeType == other.runtimeType &&
          userId == other.userId &&
          userName == other.userName;
}
