// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert`, `fetch_comments`, `path_of`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CommentResponse`, `RawComment`, `RawProfileImage`, `RawUser`

/// 取回一个作品的评论第一页。
Future<CommentPage> fetchIllustComments({required PlatformInt64 illustId}) =>
    RustLib.instance.api.crateApiCommentFetchIllustComments(illustId: illustId);

/// 按游标取下一页。`next_url` 是接口返回的完整地址。
Future<CommentPage> fetchNextComments({required String nextUrl}) =>
    RustLib.instance.api.crateApiCommentFetchNextComments(nextUrl: nextUrl);

/// 发表评论。`parent_comment_id` 非空时是回复。
Future<void> addIllustComment({
  required PlatformInt64 illustId,
  required String body,
  required PlatformInt64 parentCommentId,
}) => RustLib.instance.api.crateApiCommentAddIllustComment(
  illustId: illustId,
  body: body,
  parentCommentId: parentCommentId,
);

/// 删除自己的评论。
Future<void> deleteIllustComment({required PlatformInt64 commentId}) => RustLib
    .instance
    .api
    .crateApiCommentDeleteIllustComment(commentId: commentId);

class CommentEntry {
  final PlatformInt64 id;
  final String body;
  final String date;
  final PlatformInt64 authorId;
  final String authorName;
  final String avatarUrl;
  final bool hasReplies;

  const CommentEntry({
    required this.id,
    required this.body,
    required this.date,
    required this.authorId,
    required this.authorName,
    required this.avatarUrl,
    required this.hasReplies,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      body.hashCode ^
      date.hashCode ^
      authorId.hashCode ^
      authorName.hashCode ^
      avatarUrl.hashCode ^
      hasReplies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          body == other.body &&
          date == other.date &&
          authorId == other.authorId &&
          authorName == other.authorName &&
          avatarUrl == other.avatarUrl &&
          hasReplies == other.hasReplies;
}

class CommentPage {
  final List<CommentEntry> comments;

  /// 下一页游标，为空表示没有更多。
  final String nextUrl;

  const CommentPage({required this.comments, required this.nextUrl});

  @override
  int get hashCode => comments.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentPage &&
          runtimeType == other.runtimeType &&
          comments == other.comments &&
          nextUrl == other.nextUrl;
}
