// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_articles`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawImageUrls`, `RawSpotlightArticle`, `RawTagIllust`, `RawTrendingTag`, `SpotlightResponse`, `TrendingResponse`

/// 取回插画热门标签。
Future<List<TrendingTag>> fetchTrendingTags() =>
    RustLib.instance.api.crateApiDiscoveryFetchTrendingTags();

/// 取回插画或漫画的 Pixivision 文章。
Future<SpotlightPage> fetchSpotlightPage({required String category}) => RustLib
    .instance
    .api
    .crateApiDiscoveryFetchSpotlightPage(category: category);

/// 按服务端游标取回后续文章。
Future<SpotlightPage> fetchNextSpotlightPage({required String nextUrl}) =>
    RustLib.instance.api.crateApiDiscoveryFetchNextSpotlightPage(
      nextUrl: nextUrl,
    );

class SpotlightArticle {
  final PlatformInt64 id;
  final String title;
  final String thumbnailUrl;
  final String articleUrl;
  final String publishDate;
  final String subcategoryLabel;

  const SpotlightArticle({
    required this.id,
    required this.title,
    required this.thumbnailUrl,
    required this.articleUrl,
    required this.publishDate,
    required this.subcategoryLabel,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      thumbnailUrl.hashCode ^
      articleUrl.hashCode ^
      publishDate.hashCode ^
      subcategoryLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotlightArticle &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          thumbnailUrl == other.thumbnailUrl &&
          articleUrl == other.articleUrl &&
          publishDate == other.publishDate &&
          subcategoryLabel == other.subcategoryLabel;
}

class SpotlightPage {
  final List<SpotlightArticle> articles;
  final String nextUrl;

  const SpotlightPage({required this.articles, required this.nextUrl});

  @override
  int get hashCode => articles.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpotlightPage &&
          runtimeType == other.runtimeType &&
          articles == other.articles &&
          nextUrl == other.nextUrl;
}

class TrendingTag {
  final String tag;
  final String translatedName;
  final String thumbnailUrl;

  const TrendingTag({
    required this.tag,
    required this.translatedName,
    required this.thumbnailUrl,
  });

  @override
  int get hashCode =>
      tag.hashCode ^ translatedName.hashCode ^ thumbnailUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrendingTag &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          translatedName == other.translatedName &&
          thumbnailUrl == other.thumbnailUrl;
}
