// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `author_name`, `encode_query`, `fetch_illusts`, `page_urls`, `pick_original`, `summarize`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IllustListResponse`, `ImageUrls`, `RawIllust`, `RawMetaPage`, `RawMetaSinglePage`, `RawTag`, `SingleIllustResponse`

/// 取回推荐插画。
Future<List<IllustSummary>> fetchRecommendedIllusts() =>
    RustLib.instance.api.crateApiIllustFetchRecommendedIllusts();

/// 按关键词搜索插画。排序与匹配方式取现有版本的默认值。
Future<List<IllustSummary>> searchIllusts({required String word}) =>
    RustLib.instance.api.crateApiIllustSearchIllusts(word: word);

/// 取回自己收藏的插画。
Future<List<IllustSummary>> fetchBookmarkedIllusts() =>
    RustLib.instance.api.crateApiIllustFetchBookmarkedIllusts();

/// 取回排行。`mode` 取现有版本的取值，例如 `day`、`week`、`month`、`day_manga`。
Future<List<IllustSummary>> fetchRanking({required String mode}) =>
    RustLib.instance.api.crateApiIllustFetchRanking(mode: mode);

/// 取回相关作品。
Future<List<IllustSummary>> fetchRelatedIllusts({
  required PlatformInt64 illustId,
}) =>
    RustLib.instance.api.crateApiIllustFetchRelatedIllusts(illustId: illustId);

/// 关注动态里的插画。`restrict` 取 `public` 或 `private`。
Future<IllustPage> fetchFollowIllusts({required String restrict}) =>
    RustLib.instance.api.crateApiIllustFetchFollowIllusts(restrict: restrict);

/// 好P友的作品流。
Future<IllustPage> fetchNiceFriendIllusts() =>
    RustLib.instance.api.crateApiIllustFetchNiceFriendIllusts();

/// 按游标取下一页插画列表。
Future<IllustPage> fetchNextIllustPage({required String nextUrl}) =>
    RustLib.instance.api.crateApiIllustFetchNextIllustPage(nextUrl: nextUrl);

/// 带游标的插画列表。
Future<IllustPage> fetchIllustPage({required String path}) =>
    RustLib.instance.api.crateApiIllustFetchIllustPage(path: path);

/// 取回某个用户的作品。`illust_type` 取 `illust` 或 `manga`。
Future<List<IllustSummary>> fetchUserIllusts({
  required PlatformInt64 userId,
  required String illustType,
}) => RustLib.instance.api.crateApiIllustFetchUserIllusts(
  userId: userId,
  illustType: illustType,
);

/// 取回单个作品的详情。
Future<IllustDetail> fetchIllustDetail({required PlatformInt64 illustId}) =>
    RustLib.instance.api.crateApiIllustFetchIllustDetail(illustId: illustId);

/// 收藏一个作品。`restrict` 取 `public` 或 `private`。
Future<void> addBookmark({
  required PlatformInt64 illustId,
  required String restrict,
}) => RustLib.instance.api.crateApiIllustAddBookmark(
  illustId: illustId,
  restrict: restrict,
);

/// 取消收藏。
Future<void> removeBookmark({required PlatformInt64 illustId}) =>
    RustLib.instance.api.crateApiIllustRemoveBookmark(illustId: illustId);

/// 详情页所需的信息。
class IllustDetail {
  final PlatformInt64 id;
  final String title;
  final PlatformInt64 authorId;
  final String authorName;
  final String caption;
  final PlatformInt64 pageCount;
  final PlatformInt64 width;
  final PlatformInt64 height;
  final PlatformInt64 totalBookmarks;
  final PlatformInt64 totalView;
  final bool isBookmarked;
  final List<String> tags;

  /// 每一页的图片地址，按页序排列。
  final List<String> imageUrls;

  const IllustDetail({
    required this.id,
    required this.title,
    required this.authorId,
    required this.authorName,
    required this.caption,
    required this.pageCount,
    required this.width,
    required this.height,
    required this.totalBookmarks,
    required this.totalView,
    required this.isBookmarked,
    required this.tags,
    required this.imageUrls,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authorId.hashCode ^
      authorName.hashCode ^
      caption.hashCode ^
      pageCount.hashCode ^
      width.hashCode ^
      height.hashCode ^
      totalBookmarks.hashCode ^
      totalView.hashCode ^
      isBookmarked.hashCode ^
      tags.hashCode ^
      imageUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IllustDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authorId == other.authorId &&
          authorName == other.authorName &&
          caption == other.caption &&
          pageCount == other.pageCount &&
          width == other.width &&
          height == other.height &&
          totalBookmarks == other.totalBookmarks &&
          totalView == other.totalView &&
          isBookmarked == other.isBookmarked &&
          tags == other.tags &&
          imageUrls == other.imageUrls;
}

/// 带游标的插画列表。
class IllustPage {
  final List<IllustSummary> illusts;

  /// 下一页游标，为空表示没有更多。
  final String nextUrl;

  const IllustPage({required this.illusts, required this.nextUrl});

  @override
  int get hashCode => illusts.hashCode ^ nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IllustPage &&
          runtimeType == other.runtimeType &&
          illusts == other.illusts &&
          nextUrl == other.nextUrl;
}

/// 列表里一张作品卡片所需的信息。
class IllustSummary {
  final PlatformInt64 id;
  final String title;
  final PlatformInt64 authorId;
  final String authorName;
  final PlatformInt64 pageCount;
  final String imageUrl;

  const IllustSummary({
    required this.id,
    required this.title,
    required this.authorId,
    required this.authorName,
    required this.pageCount,
    required this.imageUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      authorId.hashCode ^
      authorName.hashCode ^
      pageCount.hashCode ^
      imageUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IllustSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          authorId == other.authorId &&
          authorName == other.authorName &&
          pageCount == other.pageCount &&
          imageUrl == other.imageUrl;
}
