// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 取回一张图片的原始字节。界面层拿到字节后自行解码显示。
Future<Uint8List> fetchImage({required String url}) =>
    RustLib.instance.api.crateApiImageFetchImage(url: url);
