// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert`, `fetch_list`, `fetch_series`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NovelListResponse`, `NovelSeriesResponse`, `RawImageUrls`, `RawNovel`, `RawSeriesDetail`, `RawSeries`, `SingleNovelResponse`

/// 取回单篇小说的详情。
Future<NovelSummary> fetchNovelDetail({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiNovelFetchNovelDetail(novelId: novelId);

/// 推荐小说。
Future<List<NovelSummary>> fetchRecommendedNovels() =>
    RustLib.instance.api.crateApiNovelFetchRecommendedNovels();

/// 自己收藏的小说。
Future<List<NovelSummary>> fetchBookmarkedNovels() =>
    RustLib.instance.api.crateApiNovelFetchBookmarkedNovels();

/// 取回系列及其章节。
Future<NovelSeries> fetchNovelSeries({required PlatformInt64 seriesId}) =>
    RustLib.instance.api.crateApiNovelFetchNovelSeries(seriesId: seriesId);

/// 按游标取系列下一页章节。
Future<NovelSeries> fetchNextSeries({required String nextUrl}) =>
    RustLib.instance.api.crateApiNovelFetchNextSeries(nextUrl: nextUrl);

/// 收藏小说。`restrict` 取 `public` 或 `private`。
Future<void> addNovelBookmark({
  required PlatformInt64 novelId,
  required String restrict,
}) => RustLib.instance.api.crateApiNovelAddNovelBookmark(
  novelId: novelId,
  restrict: restrict,
);

Future<void> removeNovelBookmark({required PlatformInt64 novelId}) =>
    RustLib.instance.api.crateApiNovelRemoveNovelBookmark(novelId: novelId);

class NovelSeries {
  final PlatformInt64 id;
  final String title;
  final String caption;
  final bool isConcluded;
  final bool isWatched;
  final List<NovelSummary> chapters;

  /// 下一页游标，为空表示没有更多。
  final String nextUrl;

  const NovelSeries({
    required this.id,
    required this.title,
    required this.caption,
    required this.isConcluded,
    required this.isWatched,
    required this.chapters,
    required this.nextUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      caption.hashCode ^
      isConcluded.hashCode ^
      isWatched.hashCode ^
      chapters.hashCode ^
      nextUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelSeries &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          caption == other.caption &&
          isConcluded == other.isConcluded &&
          isWatched == other.isWatched &&
          chapters == other.chapters &&
          nextUrl == other.nextUrl;
}

/// 小说在列表与详情里所需的信息。
class NovelSummary {
  final PlatformInt64 id;
  final String title;
  final String caption;
  final String createDate;
  final PlatformInt64 textLength;
  final PlatformInt64 totalBookmarks;
  final PlatformInt64 totalView;
  final bool isBookmarked;
  final String coverUrl;
  final PlatformInt64 authorId;
  final String authorName;
  final PlatformInt64 seriesId;
  final String seriesTitle;
  final List<String> tags;

  const NovelSummary({
    required this.id,
    required this.title,
    required this.caption,
    required this.createDate,
    required this.textLength,
    required this.totalBookmarks,
    required this.totalView,
    required this.isBookmarked,
    required this.coverUrl,
    required this.authorId,
    required this.authorName,
    required this.seriesId,
    required this.seriesTitle,
    required this.tags,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      caption.hashCode ^
      createDate.hashCode ^
      textLength.hashCode ^
      totalBookmarks.hashCode ^
      totalView.hashCode ^
      isBookmarked.hashCode ^
      coverUrl.hashCode ^
      authorId.hashCode ^
      authorName.hashCode ^
      seriesId.hashCode ^
      seriesTitle.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NovelSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          caption == other.caption &&
          createDate == other.createDate &&
          textLength == other.textLength &&
          totalBookmarks == other.totalBookmarks &&
          totalView == other.totalView &&
          isBookmarked == other.isBookmarked &&
          coverUrl == other.coverUrl &&
          authorId == other.authorId &&
          authorName == other.authorName &&
          seriesId == other.seriesId &&
          seriesTitle == other.seriesTitle &&
          tags == other.tags;
}
