// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_languages`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawGenre`, `RawGenres`, `RawLanguage`, `RawLanguages`, `RawOptions`, `RawScope`, `RawSuggestion`, `RawTools`, `SuggestionsResponse`

/// 取回关键词补全建议。
Future<List<SearchSuggestion>> fetchSearchSuggestions({required String word}) =>
    RustLib.instance.api.crateApiSearchFetchSearchSuggestions(word: word);

/// 取回与当前关键词关联的语言、制图工具和小说类型选项。
Future<SearchOptions> fetchSearchOptions({
  required String word,
  required String target,
}) => RustLib.instance.api.crateApiSearchFetchSearchOptions(
  word: word,
  target: target,
);

class SearchOption {
  final String value;
  final String label;

  const SearchOption({required this.value, required this.label});

  @override
  int get hashCode => value.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchOption &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          label == other.label;
}

class SearchOptions {
  final List<String> tools;
  final List<SearchOption> illustLanguages;
  final List<SearchOption> novelLanguages;
  final List<SearchOption> genres;

  const SearchOptions({
    required this.tools,
    required this.illustLanguages,
    required this.novelLanguages,
    required this.genres,
  });

  @override
  int get hashCode =>
      tools.hashCode ^
      illustLanguages.hashCode ^
      novelLanguages.hashCode ^
      genres.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchOptions &&
          runtimeType == other.runtimeType &&
          tools == other.tools &&
          illustLanguages == other.illustLanguages &&
          novelLanguages == other.novelLanguages &&
          genres == other.genres;
}

class SearchSuggestion {
  final String tag;
  final String translatedName;

  const SearchSuggestion({required this.tag, required this.translatedName});

  @override
  int get hashCode => tag.hashCode ^ translatedName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchSuggestion &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          translatedName == other.translatedName;
}
