// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 读取一项设置。未设置过时返回该键的默认值，键未知时返回空。
Future<String> setting({required String key}) =>
    RustLib.instance.api.crateApiStoreSetting(key: key);

Future<void> setSetting({required String key, required String value}) =>
    RustLib.instance.api.crateApiStoreSetSetting(key: key, value: value);

/// 删除一项设置，让它回到默认值。
Future<void> resetSetting({required String key}) =>
    RustLib.instance.api.crateApiStoreResetSetting(key: key);

/// 记录一次浏览。界面层按设置决定是否调用。
Future<void> recordBrowse({
  required String contentType,
  required PlatformInt64 targetId,
  required String payloadJson,
}) => RustLib.instance.api.crateApiStoreRecordBrowse(
  contentType: contentType,
  targetId: targetId,
  payloadJson: payloadJson,
);

Future<List<BrowseRecord>> listBrowse({
  required String contentType,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiStoreListBrowse(
  contentType: contentType,
  limit: limit,
  offset: offset,
);

Future<void> deleteBrowse({
  required String contentType,
  required PlatformInt64 targetId,
}) => RustLib.instance.api.crateApiStoreDeleteBrowse(
  contentType: contentType,
  targetId: targetId,
);

Future<void> clearBrowse() => RustLib.instance.api.crateApiStoreClearBrowse();

/// 记录一次搜索。同一个关键词只会留下最新一条。
Future<void> recordSearch({
  required String keyword,
  required PlatformInt64 searchType,
}) => RustLib.instance.api.crateApiStoreRecordSearch(
  keyword: keyword,
  searchType: searchType,
);

Future<List<SearchRecord>> listSearches({required PlatformInt64 recentLimit}) =>
    RustLib.instance.api.crateApiStoreListSearches(recentLimit: recentLimit);

Future<void> setSearchPinned({
  required PlatformInt64 id,
  required bool pinned,
}) => RustLib.instance.api.crateApiStoreSetSearchPinned(id: id, pinned: pinned);

Future<void> deleteSearch({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiStoreDeleteSearch(id: id);

Future<void> clearSearches() =>
    RustLib.instance.api.crateApiStoreClearSearches();

class BrowseRecord {
  final String contentType;
  final PlatformInt64 targetId;
  final String payloadJson;
  final PlatformInt64 viewedAt;

  const BrowseRecord({
    required this.contentType,
    required this.targetId,
    required this.payloadJson,
    required this.viewedAt,
  });

  @override
  int get hashCode =>
      contentType.hashCode ^
      targetId.hashCode ^
      payloadJson.hashCode ^
      viewedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BrowseRecord &&
          runtimeType == other.runtimeType &&
          contentType == other.contentType &&
          targetId == other.targetId &&
          payloadJson == other.payloadJson &&
          viewedAt == other.viewedAt;
}

class SearchRecord {
  final PlatformInt64 id;
  final String keyword;
  final PlatformInt64 searchTime;
  final PlatformInt64 searchType;
  final bool pinned;

  const SearchRecord({
    required this.id,
    required this.keyword,
    required this.searchTime,
    required this.searchType,
    required this.pinned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      keyword.hashCode ^
      searchTime.hashCode ^
      searchType.hashCode ^
      pinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          keyword == other.keyword &&
          searchTime == other.searchTime &&
          searchType == other.searchType &&
          pinned == other.pinned;
}
