// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawProfileImage`, `RawProfile`, `UserDetailResponse`

/// 取回用户资料。
Future<UserProfile> fetchUserDetail({required PlatformInt64 userId}) =>
    RustLib.instance.api.crateApiUserFetchUserDetail(userId: userId);

/// 关注一个用户。`restrict` 取 `public` 或 `private`。
Future<void> followUser({
  required PlatformInt64 userId,
  required String restrict,
}) => RustLib.instance.api.crateApiUserFollowUser(
  userId: userId,
  restrict: restrict,
);

Future<void> unfollowUser({required PlatformInt64 userId}) =>
    RustLib.instance.api.crateApiUserUnfollowUser(userId: userId);

class UserProfile {
  final PlatformInt64 id;
  final String name;
  final String account;
  final String avatarUrl;
  final String webpage;
  final PlatformInt64 totalIllusts;
  final PlatformInt64 totalManga;
  final PlatformInt64 totalNovels;
  final bool isFollowed;

  const UserProfile({
    required this.id,
    required this.name,
    required this.account,
    required this.avatarUrl,
    required this.webpage,
    required this.totalIllusts,
    required this.totalManga,
    required this.totalNovels,
    required this.isFollowed,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      account.hashCode ^
      avatarUrl.hashCode ^
      webpage.hashCode ^
      totalIllusts.hashCode ^
      totalManga.hashCode ^
      totalNovels.hashCode ^
      isFollowed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          account == other.account &&
          avatarUrl == other.avatarUrl &&
          webpage == other.webpage &&
          totalIllusts == other.totalIllusts &&
          totalManga == other.totalManga &&
          totalNovels == other.totalNovels &&
          isFollowed == other.isFollowed;
}
